version: 0.0
os: linux
files:
  - source: ngsportal.main/scripts
    destination: /home/ec2-user/deployment/scripts
hooks:
  AfterInstall:
    - location: /home/ec2-user/deployment/scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /home/ec2-user/deployment/scripts/start_application.sh
      timeout: 300
      runas: root
  ValidatesService:
    - location: /home/ec2-user/deployment/scripts/validate_service.sh
      timeout: 300
      runas: root
  
